# Generated by Django 5.2.8 on 2025-12-02 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingLectores',
            fields=[
                ('estudiante', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sesiones_iniciadas', models.IntegerField()),
                ('minutos_totales', models.FloatField()),
            ],
            options={
                'db_table': 'VISTA_RANKING_LECTORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteProfesores',
            fields=[
                ('profesor', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tareas_asignadas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reporte: Carga de Profesor',
                'verbose_name_plural': 'Reporte: Carga de Profesores',
                'db_table': 'VISTA_CARGA_PROFESORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteSeguridad',
            fields=[
                ('fecha', models.DateTimeField(primary_key=True, serialize=False)),
                ('usuario_db', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=50)),
                ('usuario_afectado', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Log de Seguridad',
                'verbose_name_plural': 'Logs de Seguridad',
                'db_table': 'VISTA_LOG_SEGURIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('carnet_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('TUTOR', 'Tutor'), ('ESTUDIANTE', 'Estudiante')], max_length=20)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel_jerarquico', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'GRADO',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'MATERIA',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neoteca.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('salario_real', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PROFESOR',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neoteca.usuario')),
                ('codigo_vinculacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100, null=True)),
                ('ingreso_mensual', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TUTOR',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Resumen del libro.', null=True)),
                ('categoria', models.CharField(choices=[('CIENCIA', 'Ciencia'), ('HISTORIA', 'Historia'), ('LITERATURA', 'Literatura')], default='LITERATURA', max_length=50)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(help_text='Sube el archivo PDF.', upload_to='libros/archivos/')),
                ('tiempo_estimado', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(blank=True, db_column='id_grado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neoteca.grado')),
            ],
            options={
                'db_table': 'LIBRO',
            },
        ),
        migrations.CreateModel(
            name='Lee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_leido_segundos', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='neoteca.usuario')),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, to='neoteca.libro')),
            ],
            options={
                'db_table': 'LEE',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='neoteca.usuario')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_creadas', to='neoteca.usuario')),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, to='neoteca.libro')),
                ('materia', models.ForeignKey(blank=True, db_column='id_materia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neoteca.materia')),
            ],
            options={
                'db_table': 'ASIGNACION',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neoteca.usuario')),
                ('datos_medicos', models.CharField(blank=True, max_length=200, null=True)),
                ('grado', models.ForeignKey(blank=True, db_column='id_grado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neoteca.grado')),
                ('tutor', models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neoteca.tutor')),
            ],
            options={
                'db_table': 'ESTUDIANTE',
            },
        ),
    ]
