# Generated by Django 5.2.8 on 2025-12-06 23:41

import django.db.models.deletion
import neoteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTareasPendientes',
            fields=[
                ('id_reporte', models.IntegerField(primary_key=True, serialize=False)),
                ('tutor', models.CharField(max_length=100)),
                ('estudiante', models.CharField(max_length=100)),
                ('libro_pendiente', models.CharField(max_length=200)),
                ('fecha_asignacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Reporte: Tarea Pendiente',
                'verbose_name_plural': 'Reporte: Tareas Pendientes',
                'db_table': 'REPORTE_TAREAS_PENDIENTES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaUsuariosSegura',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20)),
                ('email_anonimizado', models.CharField(max_length=100)),
                ('carnet_oculto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Auditoría: Usuario Seguro',
                'verbose_name_plural': 'Auditoría: Usuarios Seguros',
                'db_table': 'VISTA_USUARIOS_SEGURA',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='numero_contrato',
            new_name='grado_academico',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='salario_real',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='cuenta_bancaria',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='ingreso_mensual',
        ),
        migrations.AddField(
            model_name='libro',
            name='id_usuario_subio',
            field=models.ForeignKey(blank=True, db_column='id_usuario_subio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neoteca.usuario'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='direccion_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='codigo_vinculacion',
            field=models.CharField(default=neoteca.models.generar_codigo_tutor, max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='reporteseguridad',
            table='LOG_AUDITORIA',
        ),
    ]
