# Generated by Django 5.2.8 on 2025-12-06 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoteca', '0002_reportetareaspendientes_vistausuariossegura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='materia',
            field=models.ForeignKey(blank=True, db_column='id_materia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neoteca.materia'),
        ),
    ]
