# Generated by Django 5.2.8 on 2025-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoteca', '0003_remove_libro_categoria_libro_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros/portadas/', verbose_name='Portada del Libro'),
        ),
    ]
